api:
  x-auth: c2VyYXBpb246bW92aWVz
omdbapi:
  key: ee1c7a84
  url: https://www.omdbapi.com/
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:movies
    driver-class-name: org.h2.Driver
    username: movies
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    defer-datasource-initialization: true
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
